module.exports = {
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
    MESSAGE_SENT:"MESSAGE_SENT",
    USER_CONNECTED:"USER_CONNECTED",
    TYPING:"TYPING"
}